title Relation Schema
hide circle
entity "Choreographer" as chor {
  (PK)choreographer_id
  --
  education
  work_experience
  salary
  (FK)recommendation_id
  (FK)data_id
  (FK)user_id
}

entity "Recommendation" as recom {
  (PK)recommendation_id
  --
  meditation
  proper nutrition
  (FK)data_id
}

entity "Data" as dat {
  (PK)data_id
  --
  type_of_dance
}

entity "User" as us {
  (PK)user_id
  --
  surname
  name
  email_adress
}

recom --{ chor
dat --{ recom
chor }-- us

@enduml

